# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'BCDockerHelperGUI.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '(Get-Content ".\BCDockerHelperGUI\Properties\AssemblyInfo.cs") -replace "([0-9]*[.][0-9]*[.][0-9]*[.])([0])",''$1xxx'' | Set-Content ".\AssemblyInfo.cs"'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    msbuildArchitecture: 'x64'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'BCDockerHelperGUI\\bin\\Release\\'
    ArtifactName: 'drop'
    publishLocation: 'Container'
