# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'BCDockerHelperGUI.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  AssemblyInfoPath : './BCDockerHelperGUI/Properties/AssemblyInfo.cs'
  BuildVersion: ''

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $Version =  (Get-Content $(AssemblyInfoPath)) -replace "([0-9]*[.][0-9]*[.][0-9]*)(.0)",'$1.$(Build.BuildId)'
      $Version | Set-Content $(AssemblyInfoPath)
      $Version -match "([0-9]*[.][0-9]*[.][0-9]*[.][0-9]*)"
      $Version = $Matches[0]
      echo "##vso[task.setvariable variable=BuildVersion]$Version" 
      Get-Content $(AssemblyInfoPath)


- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    msbuildArchitecture: 'x64'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'BCDockerHelperGUI\\bin\\Release\\'
    ArtifactName: 'bin_$(BuildVersion)'
    publishLocation: 'Container'
